### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by tgmueller** [PatrikHlobil/Pandas-Bokeh#11]
Patrik,

First let me congratulate you on an amazing piece of software.   I appreciate all of your hard work!  My comments below pertain to histograms.

- It would be great if the user had the ability to change the numbers from scientific to regular numbers on the x axis.  
- It would be good if you could use actual  text of your choosing on the different axes.  Like vertical_ylabel="lbs"
- Lets say your pandas frame has two columns that are scaled quite a bit differently.  It would be wonderful if you could have both data frames overlayed on the same graph with two x axes.    Stacked with one above the other (different that overlain).   It would be good if the user could pick on the variable they want to use.

Thanks again.

**Comment by PatrikHlobil** [comment]
Hi, thanks for your comments. I'm glad that you enjoy working with **Pandas Bokeh**. Let me quickly answer your comments:

* It would be great if the user had the ability to change the numbers from scientific to regular numbers on the x axis. -> **This is already possible, however not within Pandas Bokeh, but using methods on the returning DataFrame, see this example:**

```python
import numpy as np
import pandas as pd
import pandas_bokeh
pandas_bokeh.output_notebook()

df4 = pd.DataFrame({'a': np.random.randn(1000) + 1, 'b': np.random.randn(1000),
                  'c': np.random.randn(1000) - 1}, columns=['a', 'b', 'c'])

df4 *= 1000000

p_scientific = df4.plot_bokeh.hist(show_figure=False, figsize=(500,400), xticks=range(-5000000, 50000000,1000000))

p_non_scientific = df4.plot_bokeh.hist(show_figure=False, figsize=(500,400), xticks=range(-5000000, 50000000,1000000))
p_non_scientific.below[0].formatter.use_scientific = False

pandas_bokeh.show(pandas_bokeh.row(p_scientific, p_non_scientific))
```

![image](https://user-images.githubusercontent.com/31643597/53393465-ba9c5600-399c-11e9-9a6d-f968d1a2e6c2.png)

* It would be good if you could use actual  text of your choosing on the different axes.  Like vertical_ylabel="lbs" --> **I think I don't understand this comment. I think you don't mean the x- or ylabel, which can be set easily within the API (using the xlabel and ylabel keywords)? Could you be more specific here?**

* Lets say your pandas frame has two columns that are scaled quite a bit differently.  It would be wonderful if you could have both data frames overlayed on the same graph with two x axes.    Stacked with one above the other (different that overlain).   It would be good if the user could pick on the variable they want to use. --> **Could you give an example for this?In the near future, there will be the option, to use an existing Bokeh figure (e.g. generated from Pandas Bokeh) and then plot a DataFrame on top of this. This feature is alreasy implemented in the  [GeoPandas Bokeh API](https://github.com/PatrikHlobil/Pandas-Bokeh#plot-multiple-geolayers). Do you mean something like this?**

Best,

Patrik

**Comment by tgmueller** [comment]
Dear Patrik,

Thank you so much for your response.   I'm excited that you continue to develop new features.   I took your advice and I created significant digits and added ticks (Bullet 1 in my original post).   I appreciate you taking the time to make that example.   I copied an example below and added my code.  After I sent that Github post last night, i figured out the y-axis (comment two in my original post).   My third comment above was about stacked charts.  In my example, I had them side by side seed and speeding rate which correspond to two different pandas data frames.   I was saying that it would be nice if I could put those on the same graph and have them overlay and to switch one off and the other one on.   Or both on.       This is not essential because the side by side method works great.   

One other thing I was thinking about was that it would be nice if you could zoom in the X and Y axes independently of each other. Does that make sense?

Best,
Tom  

![image](https://user-images.githubusercontent.com/9053330/53458874-5c538f80-39fd-11e9-90d3-dddd448e21ce.png)
`    # Reference: https://github.com/PatrikHlobil/Pandas-Bokeh 
    #df_hist = pd.DataFrame({'Elevation':p_df['Speed'],'AppliedRate':p_df['AppliedRate']},columns=['Speed'])
    df_speed       = pd.DataFrame ({'Speed':p_df['Speed']},            columns=['Speed'])
    df_SeedingRate = pd.DataFrame ({'AppliedRate':p_df['AppliedRate']},columns=['AppliedRate'])
    Speed_hist = df_speed.plot_bokeh(kind="hist", \
        title=str(i),       line_color="black",     hovertool  =True,     show_average=True,    xlabel="Speed[mph]", ylabel="Observations[%]",
        bins =40,           normed  = True,         cumulative = False,   show_figure=False,    xticks=range(0, 7, 1))
    SeedingRate_hist = df_SeedingRate.plot_bokeh(kind="hist", \
        title=str(i),       line_color="black",     hovertool  =True,     show_average=True,    xlabel="Seeding Rate", ylabel="Observations[%]",
        bins =40,           normed  = True,         cumulative = False,   show_figure=False,    xticks=range(0, 400000, 30000)     )     
    Speed_hist.below[0].formatter.use_scientific = False
    SeedingRate_hist.below[0].formatter.use_scientific = False
    pandas_bokeh.plot_grid([[Speed_hist, SeedingRate_hist]], plot_width=450, plot_height=300)`

**Comment by PatrikHlobil** [comment]
Dear Tom,

let me comment on your answer:

1.) There is already the option to zoom only the x- or y-axis, see GIF below. Just scroll when your cursor is over the x or y axis. ;)
![scroll](https://user-images.githubusercontent.com/31643597/53523074-1de0d200-3adc-11e9-8ec1-d77939fe9903.gif)

2.) For your example, I would not encourage you to do a histogram plot with 2 scales on the x-axis, as this probably leads to confusion (also because the units are completely different). If you would like to do this, it is probably better to go with Bokeh and create your plot on your own, since this use case is probably to special for a high-level API like here.

3.) You could try to use [Black](https://github.com/ambv/black), which I usually use for formatting my code. Just use it and your code looks **nice**. There are however also other good options like [pep8](https://pypi.org/project/pep8/) or [YAPF](https://github.com/google/yapf) that are more conventional following PEP8.

Best, Patrik

**Comment by wwymak** [comment]
To add to the non scientific notation formatting discussion, is there a way to use alternative formatting for the colorbars in geoplot? At the moment I am basically copying a chunk of your geoplot code for the colorbars but adding a bokeh `NumeralTickFormatter` to the `ColorBar`, then turn off the colorbar in `.plot_bokeh...` and then adding my colorbar to the plot.

It works but would be nice if I can just pass the number format as a param to the geoplot

**Comment by PatrikHlobil** [comment]
Hi @wwymak,

this sounds very interesting. I already thought of providing such a feature, but didn't have the time to implement this. Do you think that you could implement a option like this and submit it with a Pull Request? That would be amazing. Otherwise, could you send me a minimal example of your code, then I would try to implement it on my own. In this case, I do not have to figure out the calls on my own.

Cheers, 

Patrik

**Comment by wwymak** [comment]
@PatrikHlobil I would be happy to implement this and submit a pull request

**Comment by PatrikHlobil** [comment]
Amazing. Have you already settled out how you want to design the API for the colorbar_ticks?

**Comment by wwymak** [comment]
hmm, not fully yet. I was thinking of passing something like `colorbar_format` to `geoplot` , with it taking either a string (in which case it will be parsed by the  `NumeralTickFormatter `) or one of the classes from `bokeh.models.TickFormatter`. The default will be `None` and the standard scientific notation is used. But I am happy to use whatever you suggest

**Comment by PatrikHlobil** [comment]
It’s not about what I think, but rather which is the best solution we can come up with. I think that when 2 people think about the best solution, this will result in more options and thus an overall better solution.

I think your method with the numerical tick formatter is quite good. Also the idea that you can alternatively pass a ticker class is very smart, however in the documentation (which is sadly still the README) I would put an emphasis on the first one, because for the second on has to be familiar with the ticker classes itself.

Do you need any help from my side. Are you familiar with pull requests in GitHub? 

Cheers and thanks for you help
Patrik

**Comment by wwymak** [comment]
Okay, cool. 
> Do you need any help from my side. Are you familiar with pull requests in GitHub?

I think I am fine for now (will ping you if I have more questions) and I'm familiar with git and pull requests

**Comment by PatrikHlobil** [comment]
👍🏼
