### ISSUE TITLE
[FEATURE] Allow all keyword arguments of the figure object in `plot()`

### ISSUE THREAD

**Issue by mosc9575** [PatrikHlobil/Pandas-Bokeh#126]
Starting form this post in [SO](https://stackoverflow.com/questions/73255517/is-it-possible-to-link-axes-from-different-plots-in-pandas-bokeh-package/73274928#73274928) it looks like only a few and not all keyword arguments of the [`figure` object](http://docs.bokeh.org/en/latest/docs/reference/plotting/figure.html?highlight=figure#bokeh.plotting.figure) are evaluated in [`pandas_bokeh.plot()`](https://github.com/PatrikHlobil/Pandas-Bokeh/blob/e71bb528e001d3e32214069b8489083e29daf419/pandas_bokeh/plot.py#L249).

This has some disatvantages and the UX can be improved.

Saying this it would be really nice if a user can set the `width` and `height` and is not foreced to the defaults.

**Comment by PatrikHlobil** [comment]
Hi @mosc9575,

let me first thank your for your issue.

When I started the project I tried to replicate the matplotlib implementation of Pandas plotting API (https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.plot.html). One can argue if this turned out to be a good starting point, however I tried to mimic the basics as perfect as possible.

This of course is in stark contrast to your request, that you can pass figure keyword arguments to the plot API. If you think one step further, why should the plotting API respect the API from the bokeh.figure object, one could argue if it shouldn't accept the keyword arguments of the corresponding glyph (line, rect, etc.). I hope you get the point ;)

Therefore, I would like to close the requests, because I don't think that mixing the pandas.plotting API with bokeh.figure will be the right step. Especially when setting the width and height is as easy as using the `figsize` argument (see https://github.com/PatrikHlobil/Pandas-Bokeh#advanced-lineplot).

Best Patrik

**Comment by mosc9575** [comment]
Your explenation sounds very logical. If you want to close this issue please go ahaed, I am fine with it.
