### ISSUE TITLE
Add downstream tests to Bokeh

### ISSUE THREAD

**Issue by bryevdv** [PatrikHlobil/Pandas-Bokeh#26]
Please consider defining a subset of tests that specifically exercise your usage of Bokeh, and add them to to downstream tests we run by making a PR to edit these two files:

https://github.com/bokeh/bokeh/blob/master/scripts/ci/install.downstream
https://github.com/bokeh/bokeh/blob/master/scripts/ci/test.downstream

The downstream tests are only indicative, i.e. we never fail a build based on their result (since the problem may not be on our end end we have no control in that case) but they can be a useful leading indicator of potential compatibility problems.

**Comment by bryevdv** [comment]
@PatrikHlobil do you have any thoughts on this?

**Comment by PatrikHlobil** [comment]
@bryevdv: I started this weekend on implementing my tests on azure pipelines, but barely have any time right now. Hope I can finish it soon. Next step would be to implement the downstream tests. 

I have another question: my tests in the moment mostly test if there is no exception when creating the plots, but there is no tests if the plots are drawn correctly. How are you doing this in Bokeh? I thought about comparing the JSON representation, but also this doesn’t really work because the ids of the glyphs change every time.

Best, Patrik

**Comment by bryevdv** [comment]
>  I thought about comparing the JSON representation, but also this doesn’t really work because the ids of the glyphs change every time.


It's definitely possible to make this work, but it takes some work to make a comparison that ignores the IDs. I would suggest this route in fact. Bokeh itself runs many image-diff comparison tests, but I don't think its helpful for downstream projects to do this. Testing images is actually testing Bokeh, which is both duplicative and fragile. Your internal tests should set that you are using Bokeh correctly and as you intend to, and that you don't change your usage without meaning to. 

The downstream tests are a little different, they are mostly just to make sure that the APIs you rely on don't get upset accidentally.

**Comment by PatrikHlobil** [comment]
Added downstream tests in Bokeh master. Issue closed, thanks @bryevdv
