### ISSUE TITLE
Multipolygon holes

### ISSUE THREAD

**Issue by zifeo** [PatrikHlobil/Pandas-Bokeh#28]
Thanks for this awesome tool. Is there something specific to make sure holes are also drawn?

<img width="613" alt="image" src="https://user-images.githubusercontent.com/9053709/59423371-4ca45f00-8dd2-11e9-9ff0-127186f28376.png">

**Comment by PatrikHlobil** [comment]
Hi zifeo,

this is a feature that I have not yet implemented due to lack of time. Could you provide me a minimal example (maybe the shapefile or geojson of your example above)? However, I cannot tell you when I can implement the feature. If you are interested to have a look at it, the **magic** of the conversion of the shapely objects of the geodataframe to patches that are drawn with bokeh happens here:

```python
def convert_geoDataFrame_to_patches(gdf, geometry_column_name="geometry"):
    """Creates from a geoDataFrame with Polygons and Multipolygons a Pandas DataFrame with x any y columns specifying the geometry of the Polygons"""

    import geopandas as gpd

    gdf_new = gpd.GeoDataFrame(columns=gdf.columns)
    for i, row in gdf.iterrows():
        geometry = row[geometry_column_name]
        if geometry.type == "Polygon":
            x, y = geometry.exterior.xy
            # Convert to int for web mercador projection to save space:
            row["__x__"] = [int(_) for _ in x]
            row["__y__"] = [int(_) for _ in y]
            gdf_new = gdf_new.append(row, ignore_index=True)
        if geometry.type == "MultiPolygon":
            for polygon in geometry:
                x, y = polygon.exterior.xy
                # Convert to int for web mercador projection to save space:
                row["__x__"] = [int(_) for _ in x]
                row["__y__"] = [int(_) for _ in y]
                gdf_new = gdf_new.append(row, ignore_index=True)

    gdf_new = gdf_new.drop(columns=["geometry"])

    return gdf_new
```

I could think, that one would need to look at the polygon.interior or so.

Best, Patrik
