### ISSUE TITLE
No longer compatible with pandas >= 0.25.0

### ISSUE THREAD

**Issue by lordsutch** [PatrikHlobil/Pandas-Bokeh#34]
The most recently-released version of pandas no longer works correctly with Pandas-Bokeh, as the plotting "hooks" in pandas <= 0.24.2 no longer exist and have been replaced with a new plotting backend option described in https://github.com/pandas-dev/pandas/pull/26753. Unfortunately I'm not familiar enough with pandas' internals to write a patch to adapt the existing interface to work with pandas >= 0.25.0.

**Comment by PatrikHlobil** [comment]
Hi @lordsutch ,

thanks for the note. I am already working on this issue. The reason is the major refactoring of the plotting backend, which now allow for a switch from matplotlib to other backends (as you mentioned in the issue). I am just finishish the patch which will also allow to set the backend to Pandas Bokeh.

Best, Patrik

**Comment by PatrikHlobil** [comment]
@lordsutch : Just release the new version 0.3 of Pandas Bokeh, that fixes this issue. Thanks again for pointing out the problem.

Best Patrik
