### ISSUE TITLE
plot() method on pd.Series objects raises AttributeError

### ISSUE THREAD

**Issue by lordsutch** [PatrikHlobil/Pandas-Bokeh#36]
With Pandas-Bokeh 0.3 and Pandas 0.25.0 in a Jupyter notebook, the following code produces an AttributeError:

```python
import pandas as pd
pd.set_option('plotting.backend', 'pandas_bokeh')
pd.plotting.output_notebook()

series = pd.Series(np.random.randn(10000))
series.plot(kind='hist')
```

The full error message is:

`AttributeError: unexpected attribute 'reuse_plot' to Quad, possible attributes are bottom, fill_alpha, fill_color, hatch_alpha, hatch_color, hatch_extra, hatch_pattern, hatch_scale, hatch_weight, js_event_callbacks, js_property_callbacks, left, line_alpha, line_cap, line_color, line_dash, line_dash_offset, line_join, line_width, name, right, subscribed_events, tags or top`

Using `series.plot_bokeh(kind='hist')` works fine, however.

Adding a dummy `reuse_plot=True` argument to the `plot` method in `pandas_bokeh/plot.py` around line 154 appears to fix the problem.

https://github.com/PatrikHlobil/Pandas-Bokeh/blob/master/pandas_bokeh/plot.py#L154

**Comment by PatrikHlobil** [comment]
Hm, this is due to some weird magic that pandas.plotting does when passing the arguments to the plotting backend. I already fixed the stuff for the Dataframes, but didn’t check the Series plots. Internally, Pandas Bokeh translates the Series to a DataFrame, but before that pandas.plotting adds some more keyword arguments for backwards compatibility with Matplotlib. 

Thanks for pointing out this issue, I will try to fix it soon.

Could you try to convert your series to a DataFrame and call plot on this?

Best Patrik

**Comment by lordsutch** [comment]
I didn't have any trouble plotting DataFrame objects using the plot() method.

**Comment by PatrikHlobil** [comment]
@lordsutch ,

Thanks again for reporting this bug. I have closed just now with the fix you mentioned. With the next release of pandas-bokeh the fix should be out.

Best,

Patrik
