### ISSUE TITLE
How to add button to barh?

### ISSUE THREAD

**Issue by joshyro** [PatrikHlobil/Pandas-Bokeh#63]
Hello!!!, I Already have a grid_plot with my data but now I'm trying to update my chart with a callback, Is there a way to add a button to my template? I'm only using barh for now and my update function is already working. 
 
![image](https://user-images.githubusercontent.com/461130/79368644-56788080-7f15-11ea-9344-1f6efd999429.png)

**Comment by PatrikHlobil** [comment]
Hi @joshyro ,

I'm sure there is a way to use a callback, but that is in my opinion a to advanced feature for Pandas Bokeh. Since you are already diving deep into Bokeh (are you using Javascript or Python callbacks), I would propose that you just do the barplot in plain Bokeh. Here is a good resource for that:

https://docs.bokeh.org/en/latest/docs/user_guide/categorical.html

Escpecially with the most recent versions of Bokeh, making great plots in plain Bokeh is also pretty easy.

Best Patrik

**Comment by PatrikHlobil** [comment]
Hi @joshyro,

I would close this issue now. If you disagree, please send me a message and we discuss this issue further.

Best Patrik
